server:
  port: ${PORT}

spring:
  application:
  name: SpringBootKeycloak
#Keycloak Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
          jwk-set-uri: ${JWK_SET_URI}

jwt:
  auth:
    converter:
      resource-id: ${RESOURCE_ID}
      principal-attribute: ${PRINCIPAL_ATTRIBUTE}

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL}
  realm: ${KEYCLOAK_REALM}
  realm-master: ${KEYCLOAK_REALM_MASTER}
  cli: ${KEYCLOAK_CLI}
  user-console: ${KEYCLOAK_USER_CONSOLE}
  user-password: ${KEYCLOAK_USER_PASSWORD}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}

logging:
  level:
    org.springframework.security: ${LOGGING_LEVEL}
    org.springframework.web: ${LOGGING_LEVEL}
    org.keycloak: ${LOGGING_LEVEL}
    org.springframework.core.env: ${LOGGING_LEVEL}